language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
script: ./mvnw clean install

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

notifications:
  email: bassam.ajam95@gmail.com
